### ISSUE TITLE
Crashing on startup in Windows 11

### ISSUE THREAD

**Issue by brchristian** [anotak/doombuilderx#26]
I'm running a fresh install of Windows 11 on an Intel-based Mac using Parallels Desktop.

When I open Builder, I see:

```
UNHAPPY ERROR :(
you should save the BuilderX-lastcrash.log and post it at https://github.com/anotak/doombuilderx/issues/new.
```

So, here's the log:

```
Exception: Invalid URI: The Authority/Host could not be parsed.
Exception:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at CodeImp.DoomBuilder.General.RealMain(String[] args) in C:\DOCS\GitHub\doombuilderx\Source\Core\General\General.cs:line 610
   at CodeImp.DoomBuilder.General.Main(String[] args) in C:\DOCS\GitHub\doombuilderx\Source\Core\General\General.cs:line 560
Exception: Invalid URI: The Authority/Host could not be parsed.
Exception:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at CodeImp.DoomBuilder.General.RealMain(String[] args) in C:\DOCS\GitHub\doombuilderx\Source\Core\General\General.cs:line 610
   at CodeImp.DoomBuilder.General.Main(String[] args) in C:\DOCS\GitHub\doombuilderx\Source\Core\General\General.cs:line 560
map is null or disposed at crash time
Terminate: Immediate program termination
map is null or disposed at crash time
```

Any ideas?

**Comment by SafinW** [comment]
You can try launching DB2X in Windows 8 or 10 compatibility mode. Alternatively, there might be an issue with the configuration files. In that case, consider reinstalling DB2X to ensure that all settings and files are correctly set up.
